name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm install --save gh-pages
      - name: Set Git user for deployment
        run: |
          git config --global user.email "rohanbhirud25@gmail.com"
          git config --global user.name "rohanbhirud"
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: github.com/${{ github.repository }}
        run: |
          npx gh-pages -d build -u github-actions[bot] <github-actions[bot]@users.noreply.github.com> -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
